### ISSUE TITLE
Install advice

### ISSUE THREAD

**Issue by hvek** [dagargo/elektroid#33]
[latest Linux Mint] 

I'm sure it is obvious but I'm not successful with installation. 

 I have installed the dependencies as required, and then downloaded the "elektroid-1.3.zip" folder, but I don't know how to get this working.  I am trying to follow the instructions given to install but at the first step 

[ autoreconf --install ]

gives me:

[ autoreconf: 'configure.ac' or 'configure.in' is required ]

I also checked the folders in elektroid-1.3 to find an executable file but without success.

Where am I going wrong?

**Comment by dagargo** [comment]
The instructions in the [README.md](https://github.com/dagargo/elektroid/blob/247a3d245687b912f17b9bcd2906a002c01261c1/README.md) do not apply if you're building Elektroid from the packages.

When building from Elektroid packages, you need to proceed as with any other project already packaged with autotools.

```
$ ./configure 
$ make
$ sudo make install
```

The only difference with the  [README.md](https://github.com/dagargo/elektroid/blob/247a3d245687b912f17b9bcd2906a002c01261c1/README.md) instructions is that you don't need the packaging tools at all.

What I don't understand is why you get that error because that file is there.

```
$ unzip elektroid-1.3.zip
$ cd elektroid-1.3/
$ ls -l configure.ac 
-rw-r--r-- 1 user user 1406 feb  6 12:46 configure.ac
```

Anyway, let me know if this works for you.

**Comment by hvek** [comment]
Yes, it worked!

Thank you.
