### ISSUE TITLE
Latest release doesn't have correct requirements in INSTALL file

### ISSUE THREAD

**Issue by theo-brown** [dagargo/elektroid#59]
Hi,
I got an error running `./configure`:
```configure: error: Package requirements (libzip >= 1.1.2) were not met: No package 'libzip' found```
I have libzip5 installed already. I installed libzip-dev and everything was fine.
Is libzip-dev a requirement? Should it be added to the INSTALL instructions?

**Comment by theo-brown** [comment]
Ah I see what's happened - the README is correct, but the INSTALL script is not. I'll submit a PR.

**Comment by theo-brown** [comment]
Oh ok, this has been changed in the source code but not in the release. Maybe add a warning somewhere, or publish a new release?

**Comment by dagargo** [comment]
Sorry for the inconvenience.

I recently added the instructions to build Debian and Fedora packages to the `README.md`. In order to do so, I changed a few things and I guess this is the issue.

However, I don't think making a new release now is a good idea. Still, I'm keeping this open just in case other people faces the same situation and I'll check it carefully on the next one.

**Comment by dagargo** [comment]
Version 2.1 is almost ready.

I think everything related to the requirements was already solved but it would be very nice if you could double check it.

**Comment by dagargo** [comment]
I'm closing this as solved because, as per your comment, the only thing needed was the release itself and I'm releasing 2.1 just now.

> Oh ok, this has been changed in the source code but not in the release. Maybe add a warning somewhere, or publish a new release?
